symbolique::define_table! {
    pub struct Symbol {
        ")",
        "`'`",
        "`(`",
        "`)`",
        "`*/`",
        "`*`",
        "`+`",
        "`,`",
        "`-`",
        "`.`",
        "`/*`",
        "`//`",
        "`0`",
        "`::`",
        "`<`",
        "`>`",
        "`?`",
        "`@`",
        "`[`",
        "`\"`",
        "`\\`",
        "`]`",
        "`_`",
        "`b`",
        "`crate`",
        "`e`",
        "`fn`",
        "`in`",
        "`n`",
        "`namespace`",
        "`o`",
        "`pub`",
        "`r`",
        "`Self`",
        "`self`",
        "`super`",
        "`t`",
        "`u`",
        "`x`",
        "`{`",
        "`}`",
        "ASCII escape code",
        "binary digit",
        "block comment",
        "braced token group",
        "bracketed token group",
        "character escape code",
        "character literal",
        "comment character",
        "crate",
        "decimal digit",
        "end of file",
        "escaped space",
        "fn",
        "generic list",
        "hexadecimal digit",
        "identifier",
        "in",
        "member name",
        "namespace",
        "newline",
        "numeric literal",
        "numeric type suffix",
        "octal digit",
        "parenthesized token group",
        "path part",
        "path tree",
        "path",
        "pub",
        "punctuation",
        "Self",
        "self",
        "string character",
        "string literal",
        "super",
        "tuple type",
        "two hexadecimal digits",
        "Unicode escape sequence",
        "whitespace",
        "|",
    }
}
