symbolique::define_table! {
    pub struct Symbol {
        ")",
        "`_`",
        "`-`",
        "`->`",
        "`,`",
        "`;`",
        "`::`",
        "`:`",
        "`!`",
        "`?`",
        "`.` followed by an identifier",
        "`.`",
        "`'`",
        "`(`",
        "`)`",
        "`[`",
        "`]`",
        "`{`",
        "`}`",
        "`@`",
        "`*/`",
        "`*`",
        "`/*`",
        "`//`",
        "`/`",
        "`\"`",
        "`\\`",
        "`&&`",
        "`&`",
        "`#`",
        "`%`",
        "```",
        "`^`",
        "`+`",
        "`<`",
        "`=`",
        "`=>`",
        "`>`",
        "`|`",
        "`||`",
        "`~`",
        "`$`",
        "`0`",
        "`b`",
        "`crate`",
        "`e`",
        "`else`",
        "`false`",
        "`fn`",
        "`if`",
        "`in`",
        "`let`",
        "`loop`",
        "`mut`",
        "`n`",
        "`namespace`",
        "`o`",
        "`pub`",
        "`r`",
        "`self`",
        "`Self`",
        "`super`",
        "`t`",
        "`true`",
        "`u`",
        "`while`",
        "`x`",
        "argument name",
        "ASCII escape code",
        "binary digit",
        "binary operator",
        "block comment",
        "braced token group",
        "bracketed token group",
        "character escape code",
        "character literal",
        "comment character",
        "crate",
        "decimal digit",
        "else",
        "end of file",
        "escaped space",
        "false",
        "field name",
        "fn",
        "function name",
        "generic list",
        "hexadecimal digit",
        "identifier",
        "if",
        "in",
        "let",
        "loop",
        "member name",
        "mut",
        "namespace",
        "newline",
        "numeric literal",
        "numeric type suffix",
        "octal digit",
        "parenthesized token group",
        "path part",
        "path tree",
        "path",
        "pub",
        "punctuation",
        "self",
        "Self",
        "string character",
        "string literal",
        "super",
        "true",
        "tuple type",
        "two hexadecimal digits",
        "Unicode escape sequence",
        "variable name",
        "while",
        "whitespace",
    }
}
